export const WEATHER_ICON_MAP = {
  '0': 'fa-solid fa-sun',
  '1': 'fa-solid fa-cloud-sun',
  '2': 'fa-solid fa-cloud-sun',
  '3': 'fa-solid fa-cloud-sun',
  '45': 'fa-solid fa-smong',
  '48': 'fa-solid fa-smong',
  '51': 'fa-solid fa-cloud-rain',
  '53': 'fa-solid fa-cloud-rain',
  '55': 'fa-solid fa-cloud-rain',
  '56': 'fa-solid fa-cloud-rain',
  '57': 'fa-solid fa-cloud-rain',
  '61': 'fa-solid fa-cloud-showers-heavy',
  '63': 'fa-solid fa-cloud-showers-heavy',
  '65': 'fa-solid fa-cloud-showers-heavy',
  '66': 'fa-solid fa-cloud-showers-heavy',
  '67': 'fa-solid fa-cloud-showers-heavy',
  '71': 'fa-solid fa-snowflake',
  '73': 'fa-solid fa-snowflake',
  '75': 'fa-solid fa-snowflake',
  '77': 'fa-solid fa-snowflake',
  '80': 'fa-solid fa-cloud-showers-heavy',
  '81': 'fa-solid fa-cloud-showers-heavy',
  '82': 'fa-solid fa-cloud-showers-heavy',
  '85': 'fa-solid fa-snowflake',
  '86': 'fa-solid fa-snowflake',
  '95': 'fa-solid fa-cloud-bolt',
  '96': 'fa-solid fa-cloud-bolt',
  '99': 'fa-solid fa-cloud-bolt'
}

export const WEATHER_NAMES = {
  '0': 'Clear Sky',
  '1': 'Cloudy',
  '2': 'Cloudy',
  '3': 'Cloudy',
  '45': 'Fog',
  '48': 'Fog',
  '51': 'Drizzle',
  '53': 'Drizzle',
  '55': 'Drizzle',
  '56': 'Freezing Drizzle',
  '57': 'Freezing Drizzle',
  '61': 'Rain',
  '63': 'Rain',
  '65': 'Rain',
  '66': 'Freezing Rain',
  '67': 'Freezing Rain',
  '71': 'Snow',
  '73': 'Snow',
  '75': 'Snow',
  '77': 'Snow',
  '80': 'Rain Showers',
  '81': 'Rain Showers',
  '82': 'Rain Showers',
  '85': 'Snow Showers',
  '86': 'Snow Showers',
  '95': 'Thunderstorm',
  '96': 'Thunderstorm',
  '99': 'Thunderstorm'
}
